# Generated by Django 2.1.5 on 2019-04-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0002_producto'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
