# Generated by Django 2.1.5 on 2019-04-07 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0005_historialcompras_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historialcompras',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
