# Generated by Django 2.1.5 on 2019-04-08 01:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eshop', '0006_auto_20190407_2239'),
    ]

    operations = [
        migrations.CreateModel(
            name='PromEst',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('calificacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eshop.Producto')),
            ],
        ),
    ]
